name: Publish release

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: burrunan/gradle-cache-action@v1
        name: Publish ktor-graphql
        with:
          job-id: jdk17
          arguments: publishAllPublicationsToGitHubPackagesRepository
          gradle-version: wrapper
        env:
          USERNAME: $GITHUB_ACTOR
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
