name: Publish release

on:
  push:
    branches: [ master ]

jobs:
  test:
    name: Publish release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - uses: burrunan/gradle-cache-action@v1
        name: Publish ktor-graphql
        with:
          job-id: jdk11
          arguments: publish
          gradle-version: wrapper
        env:
          USERNAME: ${{ GITHUB_ACTOR }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
